# Generated by Django 3.0.3 on 2020-08-11 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryVisited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('country_count', models.IntegerField()),
                ('name_of_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.NameOfPerson')),
            ],
        ),
    ]
