# Generated by Django 3.0.3 on 2020-08-12 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_countryvisited'),
    ]

    operations = [
        migrations.AddField(
            model_name='nameofperson',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CountryVisited',
        ),
    ]
