# Generated by Django 3.0.3 on 2020-08-12 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20200812_0710'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NameOfPerson',
            new_name='Name',
        ),
        migrations.DeleteModel(
            name='Count',
        ),
    ]
